// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBoys.Infrastructure.Persistence;

#nullable disable

namespace TheBoys.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheBoys.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Lang_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LCID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LCID");

                    b.HasKey("Id");

                    b.ToTable("prtl_Languages", "dbo");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("News_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<DateTime?>("CurrentNewDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("currentNews_date");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("IsFeatured");

                    b.Property<DateTime?>("NewsDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("News_date");

                    b.Property<string>("NewsImg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_img");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Owner_ID");

                    b.Property<bool>("Published")
                        .HasColumnType("bit")
                        .HasColumnName("Published");

                    b.HasKey("NewsId");

                    b.ToTable("prtl_news", "dbo");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.NewsTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgAlt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Img_alt");

                    b.Property<int>("LangId")
                        .HasColumnType("int")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("NewsAbbr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Abbr");

                    b.Property<string>("NewsBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Body");

                    b.Property<string>("NewsHead")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Head");

                    b.Property<int>("NewsId")
                        .HasColumnType("int")
                        .HasColumnName("News_Id");

                    b.Property<string>("NewsSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Source");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("NewsId");

                    b.ToTable("prtl_News_Translations", "dbo");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.NewsUniv", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("News_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<DateTime?>("CurrentNewDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("currentNews_date");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("IsFeatured");

                    b.Property<DateTime?>("NewsDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("News_date");

                    b.Property<string>("NewsImg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_img");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Owner_ID");

                    b.Property<bool>("Published")
                        .HasColumnType("bit")
                        .HasColumnName("Published");

                    b.HasKey("NewsId");

                    b.ToTable("prtl_news_univ", "dbo");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.NewsUnivTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgAlt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Img_alt");

                    b.Property<int>("LangId")
                        .HasColumnType("int")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("NewsAbbr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Abbr");

                    b.Property<string>("NewsBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Body");

                    b.Property<string>("NewsHead")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Head");

                    b.Property<int>("NewsId")
                        .HasColumnType("int")
                        .HasColumnName("News_Id");

                    b.Property<string>("NewsSource")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("News_Source");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("NewsId");

                    b.ToTable("prtl_news_univ_trans", "dbo");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.NewsTranslation", b =>
                {
                    b.HasOne("TheBoys.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBoys.Domain.Entities.News", "News")
                        .WithMany("NewsTranslations")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("News");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.NewsUnivTranslation", b =>
                {
                    b.HasOne("TheBoys.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBoys.Domain.Entities.NewsUniv", "NewsUniv")
                        .WithMany("NewsUnivTranslations")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("NewsUniv");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.News", b =>
                {
                    b.Navigation("NewsTranslations");
                });

            modelBuilder.Entity("TheBoys.Domain.Entities.NewsUniv", b =>
                {
                    b.Navigation("NewsUnivTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
